apiVersion: v1
kind: Secret
metadata:
  name: finance-tracker-secrets
  namespace: default
type: Opaque
stringData:
  # Database Password
  POSTGRES_PASSWORD: "RmF2b3Vyb2ZHb2Qx"
  
  # Azure AI API Keys
  AZURE_AI_API_KEY: "N29CRkRSNWpURXkyYWR3YkZKMEd2R1hYN0w5OGxGM25RTUN2cmRsRmVjd1hQQ1hnbVQ4dUpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0dXUDFp"
  AZURE_OPENAI_KEY: "N29CRkRSNWpURXkyYWR3YkZKMEd2R1hYN0w5OGxGM25RTUN2cmRsRmVjd1hQQ1hnbVQ4dUpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0dXUDFp"
  AZURE_SEARCH_API_KEY: "UE9MOHRrcFRZT040TUxsR1QwUkxJSUdISWR6bUlWYlpuTGxYTDFoVFlTQXpTZUN3aXhNWg=="
  
  # # Azure Endpoints
  # AZURE_AIPROJECT_ENDPOINT: "https://oa-ai-demo.services.ai.azure.com/api/projects/oa-ai-demo-project"
  # CHAT_MODEL_ENDPOINT: "https://oa-ai-demo.cognitiveservices.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview"
  # AZURE_OPENAI_ENDPOINT: "https://oa-ai-demo.openai.azure.com/"
  # AZURE_AI_SEARCH_ENDPOINT: "https://oa-ai-demo.search.windows.net"
  
  # Database URL (constructed)
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOkZhdm91cm9mR29kMUBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZmluYW5jZV90cmFja2Vy"